% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Oct-2022 10:59:16
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------
                              

Mach = [2.0295712600198108 1.0001097723996544 0.24715610424201429 0.71872890492444674 ...
        5.1062926117360288 0.8886779912513767];

R = 287;

Regime = 'Transonic';
Regime = convertCharsToStrings(Regime);

Regimes = cell(1, 6);
Regimes{1} = 'Incompressible';
Regimes{2} = 'Subsonic';
Regimes{3} = 'Sonic';
Regimes{4} = 'Transonic';
Regimes{5} = 'Supersonic';
Regimes{6} = 'Hypersonic';
Regimes = convertCharsToStrings(Regimes);

SoundSpeed = [295.38258242489513 340.26264855255562 316.39922566276925 ...
              295.38258242489513 341.44145911122155 295.38258242489513];

Temp = [217.14999999999998 288.15 249.14999999999998 217.14999999999998 ...
        290.15 217.14999999999998];

VehicleSpeed = [599.5 340.3 78.2 212.3 1743.5 262.5];

gamma = 1.4;

i = 6;

